name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build app
        run: |
          xcodebuild \
          -project PCL.Mac.xcodeproj -scheme PCL.Mac -configuration Release \
          ARCHS="arm64 x86_64" ONLY_ACTIVE_ARCH=NO \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
          -archivePath build archive

      - name: Prepare app artifact directory
        run: |
          mkdir "PCL.Mac-artifact"
          mv build.xcarchive/Products/Applications/PCL.Mac.app "./PCL.Mac-artifact/PCL.Mac.app"
          mkdir "PCL.Mac-dSYMs"
          mv build.xcarchive/dSYMs/PCL.Mac.app.dSYM ./PCL.Mac-dSYMs/PCL.Mac.app.dSYM
          mv build.xcarchive/dSYMs/Core.framework.dSYM ./PCL.Mac-dSYMs/Core.framework.dSYM

      - name: Upload app artifact
        uses: actions/upload-artifact@v4
        with:
          name: PCL.Mac-${{ env.SHORT_SHA }}
          path: ./PCL.Mac-artifact
      
      - name: Upload dSYMs artifact
        uses: actions/upload-artifact@v4
        with:
          name: PCL.Mac-${{ env.SHORT_SHA }}-dSYMs
          path: ./PCL.Mac-dSYMs
